// src/stubs/auth/react/pages/Auth/ResetPassword.js
import React, { useState } from 'react'
import { Inertia } from '@inertiajs/inertia'
import { usePage } from '@inertiajs/inertia-react'

import App from '@/layouts/App'
import Button from '@/components/Button'
import TextField from '@/components/TextField'

const ResetPassword = () => {
    const { errors = {}, token, email } = usePage()

    const [form, setForm] = useState({
        token: token,
        email: email,
        password: '',
        password_confirmation: '',
    })

    const onSubmit = event => {
        event.preventDefault()
        Inertia.post(route('password.update'), form)
    }
    const onChange = (key, value) => setForm({ ...form, [key]: value })

    return (
        <App>
            <h1>Reset password</h1>

            <form onSubmit={onSubmit}>
                <TextField
                    value={form.email}
                    onChange={value => onChange('email', value)}
                    errors={errors.email}
                    type="email"
                    label="Email"
                    autoComplete="email"
                    required
                />
                <TextField
                    value={form.password}
                    onChange={value => onChange('password', value)}
                    errors={errors.password}
                    type="password"
                    label="Password"
                    autoComplete="new-password"
                    required
                />
                <TextField
                    value={form.password_confirmation}
                    onChange={value => onChange('password_confirmation', value)}
                    errors={errors.password_confirmation}
                    type="password"
                    label="Confirm Password"
                    autoComplete="new-password"
                    required
                />

                <Button type="submit">Reset Password</Button>
            </form>
        </App>
    )
}

export default ResetPassword

// src/stubs/js/pages/Auth/ResetPassword.vue
<template>
    <App>
        <h1>Reset password</h1>

        <form @submit.prevent="submit">
            <TextField
                v-model="form.email"
                :errors="$page.errors.email"
                type="email"
                label="Email"
                autocomplete="email"
                required
            />
            <TextField
                v-model="form.password"
                :errors="$page.errors.password"
                type="password"
                label="Password"
                autocomplete="new-password"
                required
            />
            <TextField
                v-model="form.password_confirmation"
                :errors="$page.errors.password_confirmation"
                type="password"
                label="Confirm Password"
                autocomplete="new-password"
                required
            />

            <Button type="submit">
                Reset Password
            </Button>
        </form>
    </App>
</template>

<script>
    import TextField from '@/components/TextField'
    import Button from '@/components/Button'
    import App from '@/layouts/App'

    export default {
        components: {
            TextField,
            Button,
            App,
        },

        data() {
            return {
                form: {
                    token: this.$page.token,
                    email: this.$page.email,
                    password: '',
                    password_confirmation: '',
                },
            }
        },

        methods: {
            submit() {
                this.$inertia.post(this.route('password.update'), this.form)
            },
        },
    }
</script>
