// src/stubs/non-auth/vue/layouts/App.vue
<template>
    <div>
        <header>
            <InertiaLink href="/">
                {{ $page.app.name }}
            </InertiaLink>
        </header>

        <p v-if="$page.session.message">
            {{ $page.session.message }}
        </p>

        <main>
            <slot />
        </main>
    </div>
</template>

// src/stubs/non-auth/react/layouts/App.js
import React from 'react'
import { InertiaLink, usePage } from '@inertiajs/inertia-react'

const App = ({ children }) => {
    const { app, session } = usePage()

    return (
        <div>
            <header>
                <InertiaLink href="/">{app.name}</InertiaLink>
            </header>

            {session.message && <p>{session.message}</p>}

            <main>{children}</main>
        </div>
    )
}

export default App
