// src/stubs/auth/react/layouts/App.js
import React, { Fragment } from 'react'
import { usePage, InertiaLink } from '@inertiajs/inertia-react'
import Post from '@/components/Post'

const App = ({ children }) => {
    const { app, auth, session } = usePage()

    const authenticated = !!auth.user

    return (
        <div>
            <header>
                <InertiaLink href={route('home')}>{app.name}</InertiaLink>

                <nav>
                    {!authenticated && (
                        <Fragment>
                            <InertiaLink href={route('login')}>
                                Login
                            </InertiaLink>
                            <InertiaLink href={route('register')}>
                                Register
                            </InertiaLink>
                        </Fragment>
                    )}
                    {authenticated && (
                        <Post
                            to={route('logout')}
                            render={({ handler }) => (
                                <a
                                    href={route('logout')}
                                    onClick={event => {
                                        event.preventDefault()
                                        handler()
                                    }}
                                >
                                    Logout
                                </a>
                            )}
                        />
                    )}
                </nav>
            </header>

            {session.verified && <p>Your email has been verified.</p>}

            {session.message && <p>{session.message}</p>}

            <main>{children}</main>
        </div>
    )
}

export default App

// src/stubs/auth/js/layouts/App.vue
<template>
    <div>
        <header>
            <InertiaLink :href="route('home')">
                {{ $page.app.name }}
            </InertiaLink>

            <nav>
                <InertiaLink v-if="!authenticated" :href="route('login')">
                    Login
                </InertiaLink>
                <InertiaLink v-if="!authenticated" :href="route('register')">
                    Register
                </InertiaLink>
                <Post
                    v-if="authenticated"
                    :to="route('logout')"
                    #default="{ handler }"
                >
                    <a :href="route('logout')" @click.prevent="handler">
                        Logout
                    </a>
                </Post>
            </nav>
        </header>

        <p v-if="$page.session.verified">
            Your email has been verified.
        </p>

        <p v-if="$page.session.message">
            {{ $page.session.message }}
        </p>

        <main>
            <slot />
        </main>
    </div>
</template>

<script>
    import Post from '@/components/Post'

    export default {
        components: {
            Post,
        },

        computed: {
            authenticated() {
                return !!this.$page.auth.user
            },
        },
    }
</script>
