// src/stubs/js/components/CheckboxField.vue
<template>
    <div>
        <input
            type="checkbox"
            :id="id"
            :checked="value"
            @change="$emit('input', $event.target.checked)"
        />
        <label v-if="label" :for="id">{{ label }}</label>
    </div>
</template>

<script>
    export default {
        props: {
            label: {
                type: String,
            },
            value: {},
        },
    }
</script>

// src/stubs/auth/react/components/CheckboxField.js
import React from 'react'
import useId from '@/helpers/use-id'

const CheckboxField = ({ label, value = false, onChange }) => {
    const id = useId()

    return (
        <div>
            <input
                type="checkbox"
                id={id}
                checked={value}
                onChange={event => onChange(event.target.checked)}
            />
            {label && <label htmlFor={id}>{label}</label>}
        </div>
    )
}

export default CheckboxField
