// src/stubs/auth/react/pages/Auth/ForgotPassword.js
import React, { useState } from 'react'
import { Inertia } from '@inertiajs/inertia'
import { usePage } from '@inertiajs/inertia-react'

import App from '@/layouts/App'
import Button from '@/components/Button'
import TextField from '@/components/TextField'

const ForgotPassword = () => {
    const { errors = {}, session = {} } = usePage()
    const [form, setForm] = useState({ email: '' })
    const onSubmit = event => {
        event.preventDefault()
        Inertia.post(route('password.email'), form)
    }

    return (
        <App>
            <h1>Reset Password</h1>

            {session.status && <p>{session.status}</p>}

            <form onSubmit={onSubmit}>
                <TextField
                    value={form.email}
                    onChange={value => setForm({ ...form, email: value })}
                    errors={errors.email}
                    type="email"
                    label="Email"
                    autoComplete="email"
                    autoFocus
                    required
                />

                <Button type="submit">Send Password Reset Link</Button>
            </form>
        </App>
    )
}

export default ForgotPassword

// src/stubs/auth/js/pages/Auth/ForgotPassword.vue
<template>
    <App>
        <h1>Reset Password</h1>

        <p v-if="$page.session.status">
            {{ $page.session.status }}
        </p>

        <form @submit.prevent="submit">
            <TextField
                v-model="form.email"
                :errors="$page.errors.email"
                type="email"
                label="Email"
                autocomplete="email"
                autofocus
                required
            />

            <Button type="submit">
                Send Password Reset Link
            </Button>
        </form>
    </App>
</template>

<script>
    import TextField from '@/components/TextField'
    import Button from '@/components/Button'
    import App from '@/layouts/App'

    export default {
        components: {
            TextField,
            Button,
            App,
        },

        data() {
            return {
                form: {
                    email: '',
                },
            }
        },

        methods: {
            submit() {
                this.$inertia.post(this.route('password.email'), this.form)
            },
        },
    }
</script>
