// src/stubs/auth/react/components/TextField.js
import React from 'react'
import useId from '@/helpers/use-id'

const TextField = ({
    type = 'text',
    label,
    value,
    errors = [],
    onChange,
    autoFocus = false,
    ...props
}) => {
    const id = useId()

    return (
        <div>
            {label && <label htmlFor={id}>{label}</label>}
            <input
                type={type}
                id={id}
                autoFocus={autoFocus}
                value={value}
                onChange={event => onChange(event.target.value)}
                {...props}
            />
            {errors.map((error, index) => (
                <span key={index}>{error}</span>
            ))}
        </div>
    )
}

export default TextField

// src/stubs/auth/vue/components/TextField.vue
<template>
    <div>
        <label v-if="label" :for="id">{{ label }}</label>
        <input
            :type="type"
            :id="id"
            :autofocus="autofocus"
            :value="value"
            @input="$emit('input', $event.target.value)"
            v-bind="$attrs"
        />
        <span v-for="error in errors">{{ error }}</span>
    </div>
</template>

<script>
    export default {
        props: {
            autofocus: {
                type: Boolean,
                default: false,
            },
            label: {
                type: String,
            },
            type: {
                default: 'text',
                validator: value =>
                    [
                        'email',
                        'number',
                        'password',
                        'search',
                        'tel',
                        'text',
                        'url',
                    ].includes(value),
            },
            value: {},
            errors: {
                type: Array,
                default: () => [],
            },
        },
    }
</script>
